### ISSUE TITLE
Collaboration Inquiry

### ISSUE THREAD

**Issue by clayton-cg** [tommybee456/ESP32-Car-Project#1]
Hi Tommy, thanks so much for sharing your great ESP32 car design! I am the founder of a small education startup called Colorgrid and have been looking for someone to help us design ESP32-based projects and their corresponding PCBs/3D print files/etc. Our first project is a simple RC 1:28 scale car and controller that use ESP-NOW to communicate. Would you be interested in a commission/freelance project? Thanks so much for considering!

P.S. I wasn't totally sure how to message you so I just opened this issue. You can reach me via email at clayton at colorgrid dot com. Feel free to close this issue! Thanks again.

**Comment by tommybee456** [comment]
Sent you an email :)
